#!/bin/bash

INSTALL_APP_DIR=$HOME/applications

# check if INSTALL_APP_DIR exist
if [ -d $INSTALL_APP_DIR ]; then
	echo "directory  '$INSTALL_APP_DIR' already exist."
else
	echo "directory  '$INSTALL_APP_DIR' does not exist."
	echo "creating... "
	mkdir $INSTALL_APP_DIR
	echo "done."
fi

echo '#Environment variables added automaticaly by applications script' >> $HOME/.bashrc
echo '#Installation directory' >> $HOME/.bashrc
echo 'export INSTALL_APP_DIR=$HOME/applications' >> $HOME/.bashrc


echo 'INSTALL_APP_DIR=$HOME/applications' >> $HOME/.bashrc
echo ' ' >> $HOME/.bashrc 


echo ' ' >> $HOME/.bashrc 
echo '# PETSc evn variables' >> $HOME/.bashrc 
echo 'export PETSC_DIR=$INSTALL_APP_DIR/petsc-2.3.3-p15-opt' >> $HOME/.bashrc 
echo 'export PETSC_ARCH=linux-gnu-c-opt' >> $HOME/.bashrc 

echo ' ' >> $HOME/.bashrc 
echo '# Update LD_LIBRARY_PATH ' >> $HOME/.bashrc 
#echo 'export LD_LIBRARY_PATH=$HOME/applications/gsl-1.9/dir-install/lib:$LD_LIBRARY_PATH' >> $HOME/.bashrc
echo 'export PATH=$HOME/applications/mpich2-1.4/dir-install/bin:$PATH' >> $HOME/.bashrc


